---
- hosts: all
  vars:
    local_root: files/
  tasks:
  - name: intall mongodb
    apt: 
      name: "{{packages}}" 
      state: present
    vars:
      packages:
      - build-essential
      - python3
      - mongodb
      - unzip
      - python-pip
    become: true
  - name: Install the latest pymongo package
    pip: name=pymongo state=latest use_mirrors=no
  - name: User admin
    mongodb_user:
      name: "admin"
      password: "admin"
      database: "admin"
      roles: readWrite,dbAdmin,userAdmin
